version: '3.8'

services:
    back-end:
        container_name: back-end
        build: 
            context: ./back-end
            dockerfile: Dockerfile
        restart: always
        depends_on:
            - data-base
        ports:
            - "8000:8000"
        env_file:
            - .env
        volumes:
            - v_data-base:/var/lib/postgresql/data
        networks:
            - ft_transcendence

    # front-end:
    #     container_name: front-end
    #     build: 
    #         context: ./front-end
    #         dockerfile: Dockerfile
    #     depends_on:
    #         - back-end
    #     ports:
    #         - "3000:3000"
    #     env_file:
    #         - .env
    #     networks:
    #         - ft_transcendence
    
    data-base:
        container_name: data-base
        build: 
            context: ./data-base
            dockerfile: Dockerfile
        restart: always
        ports:
            - "5432:5432"
        env_file:
            - .env
        volumes:
            - v_data-base:/var/lib/postgresql/data
        networks:
            - ft_transcendence

volumes:
    v_data-base:
        name: v_data-base
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /Users/zmrabet/Desktop/data
networks:
    ft_transcendence:
        name: ft_transcendence
        driver: bridge