import "bootstrap/dist/css/bootstrap.min.css";
// import BootstrapClient from '@/components/BootstrapClient.js';
import './global.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {children}
        {/* <BootstrapClient /> */}
      </body>
    </html>
  )
}
